
-- 2023.06.13 ADD

*******************************************************************************/
413.할인율(BOTTOMUP)
--DROP TABLE E_IR_DCNT_RATE_BU_IM CASCADE CONSTRAINTS PURGE;
*******************************************************************************/

CREATE TABLE E_IR_DCNT_RATE_BU_IM (
     BASE_YYMM              VARCHAR2(6)        NOT NULL
    ,APPL_BIZ_DV            VARCHAR2(10)       NOT NULL
    ,IR_MODEL_ID            VARCHAR2(20)       NOT NULL
    ,IR_CURVE_ID            VARCHAR2(20)       NOT NULL
    ,IR_CURVE_SCE_NO        NUMBER(5)          NOT NULL
    ,MAT_CD                 VARCHAR2(6)        NOT NULL
    ,SPOT_RATE_DISC         NUMBER(22,20)      NULL
    ,SPOT_RATE_CONT         NUMBER(22,20)      NULL
    ,LIQ_PREM               NUMBER(22,20)      NULL
    ,ADJ_SPOT_RATE_DISC     NUMBER(22,20)      NULL
    ,ADJ_SPOT_RATE_CONT     NUMBER(22,20)      NULL
    ,ADD_SPRD               NUMBER(22,20)      NULL
    ,LAST_MODIFIED_BY       VARCHAR2(100)      NULL
    ,LAST_UPDATE_DATE       DATE               NOT NULL
)
; -- TABLESPACE TS_GESG_DAT01;

CREATE UNIQUE INDEX E_IR_DCNT_RATE_BU_IM_PK ON E_IR_DCNT_RATE_BU_IM
(
     BASE_YYMM       ASC
    ,APPL_BIZ_DV     ASC
    ,IR_MODEL_ID     ASC
    ,IR_CURVE_ID     ASC
    ,IR_CURVE_SCE_NO ASC
    ,MAT_CD          ASC
)
; -- TABLESPACE TS_GESG_IDX01
;

ALTER TABLE E_IR_DCNT_RATE_BU_IM ADD CONSTRAINT E_IR_DCNT_RATE_BU_IM_PK PRIMARY KEY(BASE_YYMM,APPL_BIZ_DV,IR_MODEL_ID,IR_CURVE_ID,IR_CURVE_SCE_NO,MAT_CD);

-- GRANT INSERT ON E_IR_DCNT_RATE_BU_IM TO GESG_ROLE;
-- GRANT UPDATE ON E_IR_DCNT_RATE_BU_IM TO GESG_ROLE;
-- GRANT DELETE ON E_IR_DCNT_RATE_BU_IM TO GESG_ROLE;
-- GRANT SELECT ON E_IR_DCNT_RATE_BU_IM TO GESG_ROLE;
-- GRANT SELECT ON E_IR_DCNT_RATE_BU_IM TO GESG_SEL_ROLE;

--DROP   PUBLIC SYNONYM E_IR_DCNT_RATE_BU_IM FORCE;
-- CREATE PUBLIC SYNONYM E_IR_DCNT_RATE_BU_IM FOR E_IR_DCNT_RATE_BU_IM;

COMMENT ON TABLE  E_IR_DCNT_RATE_BU_IM                        IS '할인율(BOTTOMUP)';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.BASE_YYMM              IS '기준년월';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.APPL_BIZ_DV            IS '적용업무구분';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.IR_MODEL_ID            IS '금리모형ID';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.IR_CURVE_ID            IS '금리곡선ID';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.IR_CURVE_SCE_NO        IS '금리곡선시나리오번호';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.MAT_CD                 IS '만기코드';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.SPOT_RATE_DISC         IS '현물금리(년)';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.SPOT_RATE_CONT         IS '현물금리(연속)';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.LIQ_PREM               IS '유동성프리미엄';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.ADJ_SPOT_RATE_DISC     IS '조정현물금리(년)';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.ADJ_SPOT_RATE_CONT     IS '조정현물금리(연속)';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.ADD_SPRD               IS '가산스프레드';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.LAST_MODIFIED_BY       IS '최종수정자';
COMMENT ON COLUMN E_IR_DCNT_RATE_BU_IM.LAST_UPDATE_DATE       IS '최종수정일자';
;




CREATE TABLE E_IR_DCNT_SCE_IM (
     BASE_YYMM            VARCHAR2(6)      NOT NULL
    ,APPL_BIZ_DV          VARCHAR2(10)     NOT NULL
    ,IR_MODEL_ID          VARCHAR2(20)     NOT NULL
    ,IR_CURVE_ID          VARCHAR2(20)     NOT NULL
    ,IR_CURVE_SCE_NO      NUMBER(5)        NOT NULL
    ,MAT_CD               VARCHAR2(6)      NOT NULL
    ,SPOT_RATE            NUMBER(22,20)    NULL
    ,FWD_RATE             NUMBER(22,20)    NULL
    ,LAST_MODIFIED_BY     VARCHAR2(100)    NULL
    ,LAST_UPDATE_DATE     DATE             NOT NULL
)
; -- TABLESPACE TS_GESG_DAT01;

CREATE UNIQUE INDEX E_IR_DCNT_SCE_IM_PK ON E_IR_DCNT_SCE_IM
(
     BASE_YYMM       ASC
    ,APPL_BIZ_DV     ASC
    ,IR_MODEL_ID     ASC
    ,IR_CURVE_ID     ASC
    ,IR_CURVE_SCE_NO ASC
    ,MAT_CD          ASC
)
; -- TABLESPACE TS_GESG_IDX01;

ALTER TABLE E_IR_DCNT_SCE_IM ADD CONSTRAINT E_IR_DCNT_SCE_IM_PK PRIMARY KEY(BASE_YYMM,APPL_BIZ_DV,IR_MODEL_ID,IR_CURVE_ID,IR_CURVE_SCE_NO,MAT_CD);

-- GRANT INSERT ON E_IR_DCNT_SCE_IM TO GESG_ROLE;
-- GRANT UPDATE ON E_IR_DCNT_SCE_IM TO GESG_ROLE;
-- GRANT DELETE ON E_IR_DCNT_SCE_IM TO GESG_ROLE;
-- GRANT SELECT ON E_IR_DCNT_SCE_IM TO GESG_ROLE;
-- GRANT SELECT ON E_IR_DCNT_SCE_IM TO GESG_SEL_ROLE;

--DROP   PUBLIC SYNONYM E_IR_DCNT_SCE_IM FORCE;
-- CREATE PUBLIC SYNONYM E_IR_DCNT_SCE_IM FOR E_IR_DCNT_SCE_IM;

COMMENT ON TABLE  E_IR_DCNT_SCE_IM                     IS '목적별 할인율 시나리오(내부모형)';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.BASE_YYMM           IS '기준년월';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.APPL_BIZ_DV         IS '적용업무구분';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.IR_MODEL_ID         IS '금리모형ID';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.IR_CURVE_ID         IS '금리곡선ID';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.IR_CURVE_SCE_NO     IS '금리곡선시나리오번호';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.MAT_CD              IS '만기코드';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.SPOT_RATE           IS '현물금리';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.FWD_RATE            IS '선도금리(1M)';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.LAST_MODIFIED_BY    IS '최종수정자';
COMMENT ON COLUMN E_IR_DCNT_SCE_IM.LAST_UPDATE_DATE    IS '최종수정일자';
